a = int(input("Ballni kiriting:"))
b = int(input("Ballni kiriting:"))
c = int(input("Ballni kiriting:"))
d = int(input("Ballni kiriting:"))
e = int(input("Ballni kiriting:"))
f = int(input("Ballni kiriting:"))
g = int(input("Ballni kiriting:"))
h = int(input("Ballni kiriting:"))
i = int(input("Ballni kiriting:"))
j = int(input("Ballni kiriting:"))
result = (a + b + c + d + e + f + g + h + i + j)
print(result)